### ISSUE TITLE
wrapper functions required

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/libbpf#7]
Implement of the following wrapper functions is currently required to attach any ebpf program:
- getprogram()
- attachkprobe()
- traceprint()

**Comment by geyslan** [comment]
@Ankurk99 I'll work on it asap.

**Comment by geyslan** [comment]
I noticed that `TracePrint()` is no longer in the [libbpfgo.go](https://github.com/aquasecurity/libbpfgo/blob/main/libbpfgo.go) codebase. It was moved to [helpers](https://github.com/aquasecurity/libbpfgo/blob/main/helpers/) module and named `TracePipeListen()` https://github.com/aquasecurity/libbpfgo/blob/391db9565ae877caa14423f5999b6847ef085ad5/helpers/tracelisten.go#L15-L33.

@Ankurk99 Is `TracePipeListen()` really necessary at this moment? If not, as we're building the KA libbpf as 1:1 to kernel libbpf, I would like to defer its implementation into a sub-module to be created.

**Comment by Ankurk99** [comment]
Ah sure, we can do it's implementation later.

**Comment by geyslan** [comment]
@Ankurk99, be my guest to test the changes. It would be grand if you could create the `tests/progs.go` and `tests/progs.bpf.c` and raise a PR with them.
